# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160712202006 on 2016-07-13 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondtestmodel',
            name='name',
        ),
    ]
