# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160712202006 on 2016-07-13 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160713_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='new_name',
        ),
    ]
