# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160713133908 on 2016-07-13 14:10
from __future__ import unicode_literals

from django.db import migrations
import django.core.management.commands.loaddata
from django.db import DEFAULT_DB_ALIAS
import os


fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), 'fixtures'))
fixture_filename = 'data3173.json'


def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    load_command = django.core.management.commands.loaddata.Command()

    options = {
        'ignore': False,
        'database': DEFAULT_DB_ALIAS,
        'app_label': None,
        'verbosity': 0,
        'exclude': [],
        'project_apps': apps
    }

    load_command.handle(fixture_file, **options)
    print(1 / 0)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', u'0002_remove_secondtestmodel_name'),
        ('myapp', u'0003_remove_testmodel_new_name'),
    ]

    operations = [
         migrations.RunPython(load_fixture),
    ]
